spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace

token:
  secret: test
  access-token-expiration-seconds: 7200 # 2시간
  temporary-token-expiration-seconds: 600 # 10분